#pragma once

enum g_tileType {
    CUBE,
    STAIR_SOUTHEAST,
    STAIR_SOUTHWEST,
    STAIR_NORTHWEST,
    STAIR_NORTHEAST,
    RAMP_SOUTHEAST,
    RAMP_SOUTHWEST,
    RAMP_NORTHWEST,
    RAMP_NORTHEAST,
    CUBE_HOLE_TOP,
    CUBE_HOLE_SOUTHEAST,
    CUBE_HOLE_SOUTHWEST,
    EMPTY
};

